export const getVinylCards = () => [
  {
    id: 1,
    name: "Nothing's Gonna Hurt You Baby",
    artist: "Cigarettes After Sex",
    image: {
      x1: "./src/assets/image1@1x.jpg",
      x2: "./src/assets/image1@1x.jpg",
    },
    year: 2010,
    country: "USA",
    genreId: 3,
    styles: ["Punk", "Dub", "Funk"],
  },
  {
    id: 2,
    name: "Let It Be",
    artist: "The Beatles",
    image: {
      x1: "./src/assets/image2@1x.jpg",
      x2: "./src/assets/image1@1x.jpg",
    },
    year: 1960,
    country: "UK",
    genreId: 5,
    styles: ["Rock", "Dub", "Funk"],
  },
  {
    id: 3,
    name: "Paint The Town Red",
    artist: "Doja Cat",
    image: {
      x1: "./src/assets/image3@1x.jpg",
      x2: "./src/assets/image3@1x.jpg",
    },
    year: 2023,
    country: "USA",
    genreId: 4,
    styles: ["Punk", "Dub", "Funk"],
  },
  {
    id: 4,
    name: "Who Let The Dogs Out",
    artist: "Baha Men",
    image: {
      x1: "./src/assets/image4@1x.jpg",
      x2: "./src/assets/image4@1x.jpg",
    },
    year: 2000,
    country: "USA",
    genreId: 4,
    styles: ["House", "Ragga", "Hip-Hop"],
  },
  {
    id: 5,
    name: "U Can't touch this",
    artist: "MC Hammer",
    image: {
      x1: "./src/assets/image5@1x.jpg",
      x2: "./src/assets/image5@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Rap", "Ragga", "Hip-Hop"],
  },
  {
    id: 6,
    name: "Ra-Ta-Ta",
    artist: "Wencke Myhre",
    image: {
      x1: "./src/assets/image7@1x.jpg",
      x2: "./src/assets/image7@1x.jpg",
    },
    year: 1970,
    country: "Germany",
    genreId: 4,
    styles: ["Electronic", "Ragga", "Hip-Hop"],
  },
  {
    id: 7,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image8@1x.jpg",
      x2: "./src/assets/image8@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 8,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image9@1x.jpg",
      x2: "./src/assets/image9@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 9,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image10@1x.jpg",
      x2: "./src/assets/image10@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 10,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image11@1x.jpg",
      x2: "./src/assets/image11@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 11,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image12@1x.jpg",
      x2: "./src/assets/image12@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 12,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image13@1x.png",
      x2: "./src/assets/image13@1x.png",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 13,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image14@1x.jpg",
      x2: "./src/assets/image14@1x.jpg",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 14,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image15@1x.png",
      x2: "./src/assets/image15@1x.png",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 15,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image16@1x.png",
      x2: "./src/assets/image16@1x.png",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 16,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image17@1x.png",
      x2: "./src/assets/image17@1x.png",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 17,
    name: "Let There Be Rock",
    artist: "AC/DC",
    image: {
      x1: "./src/assets/image18@1x.png",
      x2: "./src/assets/image18@1x.png",
    },
    year: 1990,
    country: "USA",
    genreId: 4,
    styles: ["Electronic", "Rock", "Hip-Hop"],
  },
  {
    id: 18,
    name: "Nothing's Gonna Hurt You Baby",
    artist: "Cigarettes After Sex",
    image: {
      x1: "./src/assets/image19@1x.jpg",
      x2: "./src/assets/image19@1x.jpg",
    },
    year: 2010,
    country: "USA",
    genreId: 3,
    styles: ["Punk", "Dub", "Funk"],
  },
];
export const getGenres = () => [
  {
    id: 1,
    name: "Jazz",
    color: "#ffc3f3",
    textTheme: "dark",
  },
  {
    id: 2,
    name: "Country",
    color: "#ffa161",
    textTheme: "light",
  },
  {
    id: 3,
    name: "Alternative",
    color: "#ffa161",
    textTheme: "light",
  },
  {
    id: 4,
    name: "Pop",
    color: "#ffa161",
    textTheme: "light",
  },
  {
    id: 5,
    name: "Rock",
    color: "#ffa161",
    textTheme: "light",
  },
];
